language: android

jdk:
  - oraclejdk7
  - openjdk7

android:
  components:
    - build-tools-20.0.0
    - android-16
  licenses:
    - android-sdk-license-5be876d5

env:
  global:
    - secure: "5HEMMANWjrHtueonXKz/G3WCdbTk3VXGe+HpCkCqlbNJJSxrvg+mh4mc6+/JDBCRh2DvkJhQOnbFjGD94C+QD/8LywOJiu687w6wDG9vKGCuVMzIdZajemNof0MG0IPdGYz9gtife8/lQhQ/Og07WrXJMqH0SvFI3p95T6DIFe2p39JfZsnh6T6QAT1L+vElzqM6kZtvqlZCtbfW8Dbu359EJIjaCluxGAUtFafxTLWUHXnahuysluqMYV/OgbP39GfXxxo77LTXjJp/78Yv2L3tSOZK+2AUimOPKW98aaqCb002s8t7clMkpvSlL90/gfCVWqAjafGMXjsqU11/dxKrQ8dh1ZXEk/WGXVOhwoFILQMt/jas5z94dMw1kYGv8jWMqicivE/GlUUhNhqCOgfESPyTOT2Mn9YAWxr3tOlUy5UhwJva1mc8ZN05GKpzsdsNXuT29nLKS2zVtQE7qiorSDI7rWWqxsT+HaQLSa8jz/vRTYpg4pUIG3IPMjEJIeDHqIeYHvgU9PhYYXpROWRpZ5wtde+STfVeb9yycxN52k0zOKOJthyMS8gTdkH6Movz97JGtvyvzYFXMxOr455od6SvVBwHiZ3NdkZhrdyyGmqX62oAu6K5hnDT/of03AJxzP4VMElduXEYy7aWmPRrBEJMXGrvM2r82tXCkPQ="
    - secure: "khFhYpRDFb7dkrvLBMjyrjHwkop+K1x1Hbrl+vy6yyYMBtZNqZZXT+FVlVZu8ZWRUaM2y5POzSgGCwN1cTfil19p+DtGJxJDk5Rc/FzdUI2+xLCc/ExUuvnxozRG1Wau+fGhNwNs9whnlZkzb3ZOqrcvQKcCZiHyqMlXbIY98qiRG1TpVrdqUyGSiuzMMa3BhDoQPYR9qQYVCX2r8MBHTQTxd5InFJ1Em73ablwiIoHpj8Ly9lg5bRL1Up4U17GWnYzUQFxL8QfDHDtJcnqO7gGIEE3Hs7UR6JOkUx2Tjn3/IV45pysqm+Eee9TUy7EHDhWKAEIGwXeso0HlmYdfoshR6e4nV7P0vioVdRYuryjVAcazpQXDmkasiB8oTkXB9Ca2HMjJYcWyM9mmrCHJMTQlW/t937IZqGWN0MQRx0GW8WRY7nUzeRougjFSOQ0t79tBFHPnDuO6+iL68m9Vs4Sv8wtFAn8a2NAbkZcKL5nxpSRCWrvOVdZQkLjNtsViFQRDXfDhBA9cr9OeI5Orbc9y4oN/USLLg6HspEvR3/G6orh8Y3fdwW4cf9Ako6N1cdwRcunBYHR8CSVHCED54xpUpARrWZE9GFbEeC3tkn5Rb+0R4Jmcsz+hhRqADpXwEAfA250/xV639p/OQzQGsUpRyhLBqwCTXyPFsDWMAKI="

after_success:
  - continuous-integration/publish-snapshot.sh
